#! /bin/sh
### BEGIN INIT INFO
# Provides:          mount_shares
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mount NFS shares
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

do_stop () {
	if mount | grep -q movies
	then
		umount /var/movies
		umount /var/materials
	fi
}

do_start () {
	mount -t nfs -o ro,bg,nolock,ac,acregmin=6000 fair:/media/FAIR/data/movies /var/movies
	mount -t nfs -o bg fair:/home/teacher/materials /var/materials
}

case "$1" in
  start)
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	do_stop
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
